// Generated by CoffeeScript 1.4.0
(function() {
  var CozySocketListener;

  module.exports = CozySocketListener = (function() {

    function CozySocketListener() {}

    CozySocketListener.prototype.brunchPlugin = true;

    CozySocketListener.prototype.include = ["../lib/client.js"];

    CozySocketListener.serverInitializer = require('./server');

    return CozySocketListener;

  })();

}).call(this);
