// Generated by CoffeeScript 1.4.0
(function() {
  var SocketListener;

  module.exports = SocketListener = (function() {

    function SocketListener() {}

    SocketListener.prototype.brunchPlugin = true;

    SocketListener.prototype.include = ["../lib/client.js"];

    return SocketListener;

  })();

  module.exports.serverInitializer = require('./server');

}).call(this);
