// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(compound, patterns) {
    var client, pattern, redis, sio, _i, _len, _results;
    sio = require('socket.io');
    compound.io = sio.listen(compound.server);
    compound.io.set('log level', 2);
    compound.io.set('transports', ['websocket']);
    redis = require('redis');
    client = redis.createClient();
    console.log(' socket.io initialized !');
    client.on('pmessage', function(pat, ch, msg) {
      console.log(pat, ch, msg);
      return compound.io.sockets.emit(ch, msg);
    });
    _results = [];
    for (_i = 0, _len = patterns.length; _i < _len; _i++) {
      pattern = patterns[_i];
      _results.push(client.psubscribe(pattern));
    }
    return _results;
  };

}).call(this);
